### ISSUE TITLE
Error: protocol must be either "_tcp" or "_udp" but is "_apple-mobdev2"

### ISSUE THREAD

**Issue by simwq123** [mdns-js/node-mdns-js#63] opened 2016-12-26 08:49 UTC
Dose anybody else meet this issue? How to solve this

E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:258
    throw new Error('protocol must be either "_tcp" or "_udp" but is "' +
    ^

Error: protocol must be either "_tcp" or "_udp" but is "_apple-mobdev2"
    at checkProtocolU (E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:258:11)
    at fromString (E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:105:3)
    at new exports.ServiceType (E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:30:14)
    at E:\jsCode\test\node_modules\mdns-js\lib\decoder.js:40:27
    at E:\jsCode\test\node_modules\mdns-js\node_modules\dns-js\lib\dnspacket.js:223:7
    at Array.forEach (native)
    at each (E:\jsCode\test\node_modules\mdns-js\node_modules\dns-js\lib\dnspacket.js:221:17)
    at module.exports.decodeSection (E:\jsCode\test\node_modules\mdns-js\lib\decoder.js:26:10)
    at E:\jsCode\test\node_modules\mdns-js\lib\decoder.js:111:5
    at Array.forEach (native)

**Comment by kmpm** [comment] 2016-12-27 12:58
Interesting. 
If you have a look at the readme file about debugging you can find more information about how to get more information.

I can't really do much as it is. But I can tell you that it is unexpected to see another protocol than TCP or UDP. It might very well be some kind av parsing error in mdns-js.

**Comment by simwq123** [comment] 2016-12-28 08:47
![image](https://cloud.githubusercontent.com/assets/19643699/21517718/688b4c02-cd1c-11e6-9aa7-a24113ef4490.png)
I debug it，and this is the log. I think the issue is in service_type.js file at line 81. May be parse the string error.

**Comment by kmpm** [comment] 2016-12-29 07:41
You do probably, somewhere out of screen, have a message or many labeled __mdns:inbound__
I would like to have those if possible. If you have a lot of other messages and it's hard to get try to filter on only those by using _DEBUG=mdns:inbound_

**Comment by simwq123** [comment] 2016-12-30 02:27
I cannot reproduce the problem Yesterday. Now I reproduce it and I have found someone and I met the same problem, this is my debug log:

```
 mdns:inbound incoming message 000084000000000400000000095f7365727669636573075f646e732d7364045f756470056c6f63616c00000c000100001194000c045f737368045f746370c023c00c000c000100001194000c095f736674702d737368c039c00c000c0001000011940007045f736d62c039c00c000c000100001194000e0b5f6166706f766572746370c039 +13ms
  mdns:inbound incoming message 000084000000000100000000095f7365727669636573075f646e732d7364045f756470056c6f63616c00000c0001000000ff0012055f6d69696f045f756470056c6f63616c00 +4ms
data:  { addresses: [ '192.168.1.34' ],
  query: [],
  type:
   [ { name: 'miio',
       protocol: 'udp',
       subtypes: [],
       description: undefined } ],
  interfaceIndex: 4,
  networkInterface: 'pseudo multicast' }
  mdns:inbound incoming message 000084000000000100000000095f7365727669636573075f646e732d7364045f756470056c6f63616c00000c0001000000ff0012055f6d69696f045f756470056c6f63616c00 +3ms
  mdns:inbound incoming message 000084000001001000000000095f7365727669636573075f646e732d7364045f756470056c6f63616c00000c0001c00c000c000100000e0f0010085f61697264726f70045f746370c023c00c000c000100000e0f000c095f736674702d737368c043c00c000c000100000e0f0008055f6d69696fc01ec00c000c000100000e0f000c095f6e7673747265616dc043c00c000c000100000e0f000b085f7072696e746572c043c00c000c000100000e0f0016045f7375620e5f6170706c652d6d6f6264657632c043c00c000c000100000e0f0002c0b6c00c000c000100000e0f0007045f697070c043c00c000c000100000e0f000b085f7363616e6e6572c043c00c000c000100000e0f000e0b5f6166706f766572746370c043c00c000c000100000e0f000b085f686f6d656b6974c043c00c000c000100000e0f0008055f69707073c043c00c000c000100000e0f00120f5f70646c2d6461746173747265616dc043c00c000c000100000e0f0007045f737368c043c00c000c000100000e0f0007045f736d62c043c00c000c000100000e0f0008055f68747470c043 +10ms
E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:258
    throw new Error('protocol must be either "_tcp" or "_udp" but is "' +
    ^

Error: protocol must be either "_tcp" or "_udp" but is "_apple-mobdev2"
    at checkProtocolU (E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:258:11)
    at fromString (E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:105:3)
    at new exports.ServiceType (E:\jsCode\test\node_modules\mdns-js\lib\service_type.js:30:14)
    at E:\jsCode\test\node_modules\mdns-js\lib\decoder.js:40:27
    at E:\jsCode\test\node_modules\mdns-js\node_modules\dns-js\lib\dnspacket.js:223:7
    at Array.forEach (native)
    at each (E:\jsCode\test\node_modules\mdns-js\node_modules\dns-js\lib\dnspacket.js:221:17)
    at module.exports.decodeSection (E:\jsCode\test\node_modules\mdns-js\lib\decoder.js:26:10)
    at E:\jsCode\test\node_modules\mdns-js\lib\decoder.js:111:5
    at Array.forEach (native)
```

**Comment by kmpm** [comment] 2016-12-30 07:39
This issue was first but since it was first identified in 66 I'm marking it as a duplicate of #66

**Closed by kmpm** 2016-12-30 07:39 UTC
Labels: bug, duplicate
